### PR TITLE
Install Plugin on Launch, Added unit tests

### LINKED ISSUE #67: Container Plugin Installation
Add a method to install a configured STT plugin on container start so containers may implement arbitrary STT plugins

### PR DESCRIPTION
**Pull request by NeonDaniel**
Add unit tests with automation
Add cli entry point to install plugin on module run
Add util for pip installing plugins
Closes #67 
#50

### CODE REVIEW

**Comment by NeonDaniel** [comment]
rebase on https://github.com/NeonGeckoCom/neon-skill-utils/pull/294
test after https://github.com/NeonGeckoCom/neon-stt-plugin-polyglot/pull/6

**Comment by NeonDaniel** [comment]
I found it useful to put model files in the config directory (mounted to `/config` in the container). I am using the `neon-stt-plugin-deepspeech-stream-local` plugin (some issues with the Polyglot plugin signatures).

It also appears that the models we download in Polyglot can be used with the streaming STT implementation here; @NeonMariia @NeonBohdan do you have opinions on porting the plugin download methods into this plugin to get streaming STT support?

example stt config:
```yaml
stt:
  module: deepspeech_stream_local
  deepspeech_stream_local:
    model_path: /config/polyglot_en.pbmm
    scorer_path: /config/polyglot-en.scorer
```

**Comment by NeonBohdan** [comment]
> I found it useful to put model files in the config directory (mounted to `/config` in the container). I am using the `neon-stt-plugin-deepspeech-stream-local` plugin (some issues with the Polyglot plugin signatures).
> 
> It also appears that the models we download in Polyglot can be used with the streaming STT implementation here; @NeonMariia @NeonBohdan do you have opinions on porting the plugin download methods into this plugin to get streaming STT support?
> 
> example stt config:
> 
> ```yaml
> stt:
>   module: deepspeech_stream_local
>   deepspeech_stream_local:
>     model_path: /config/polyglot_en.pbmm
>     scorer_path: /config/polyglot-en.scorer
> ```

Yes, it's possible 
As both uses deepspeech to run models 
But as I see download isn't a part of plugin(need to provide path to model)
But there are some ways to download via CLI or something else

**Comment by JarbasAl** [comment]
in the vosk model i download the model automatically if:
- model not set, i keep list of lang:url for default models
- model is a url

just want to point out a possible issue, if speech client loads before there is internet then the download will fail, i ran into this issue with vosk. So we need to check for internet and if there is no internet we need to react to internet connected bus event and delay the download until then

**Comment by NeonDaniel** [comment]
> in the vosk plugin i download the model automatically if:
> 
> * model not set, i keep list of lang:url for default models
> * model is a url
> 
> just want to point out a possible issue, if speech client loads before there is internet then the download will fail, i ran into this issue with vosk. So we need to check for internet and if there is no internet we need to react to internet connected bus event and delay the download until then

This makes sense; in Polyglot, we handle the first case, but a URL spec makes a lot of sense too.

**Review by JarbasAl — APPROVED** [review]

**Pull request merged**
